apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  labels:
    app: bee
  name: beekman-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bee
  template:
    metadata:
      labels:
        app: bee
    spec:
      containers:
      - env:
        - name: RUN_TYPE
          value: cpu
        - name: CPU_PERCENT
          value: "100"
        image: beekman9527/cpumemload:latest
        name: beekman-1
        resources:
          limits:
            cpu: 100m
            memory: 12Mi
          requests:
            cpu: 10m
            memory: 10Mi
      imagePullSecrets:
      - name: docker-credentials
